name: "Feedable"
description: "Get started with Python Container actions"
author: "Jacob Tomlinson"
inputs:
  folderPath:
    description: "Folder path e.g. contents/images"
    default: "images"
  outputPath:
    description: "Output path e.g. _layouts/feed.xml"
    default: "web/feed.xml"
  title:
    description: "Title of the feed"
    default: "My Feed"
  description:
    description: "Description of the feed"
    default: "My feed description"
  baseUrl:
    description: "Base URL of the site"
    default: "https://example.com"
  author:
    description: "Author of the feed"
    default: "Author"
  directLink:
    description: "Base direct links to the images"
    default: "https://example.com"

outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
