name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@master

      - name: Self test
        id: selftest
        # Put your action repo here
        uses: yiran-frank-mao/feedable@master
        with:
          directLink: "https://raw.githubusercontent.com/yiran-frank-mao/feedable/master"

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update feed
